backend:
  name: github
  repo: sudosoc/sudosoc
  branch: main
  auth_scope: repo
  client_id: Ov23lied924oRTMarvbo

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
